version: '3.8'

services:
  docker-monitor-bot:
    build: .
    container_name: docker-monitor-bot
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
